apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  timeout: 3m
  ref:
    branch: main
  secretRef:
    name: github-auth
  url: https://github.com/andisor2005/virtual-org-demo.git
  ignore: |
    .git/
    .github/
